### ISSUE TITLE
Measurement Details page sometimes loads twice

### ISSUE THREAD

**Issue by wrandall22** [GlobalTechnology/gma-android#42]
Sometimes the Measurement Details Activity will load from local storage and from the API in the same page load.  This ends up creating two legends instead of one.  Also, it is throwing off attempts to save measurements.

**Comment by wrandall22** [comment]
More accurately, it appears that the ContentLoader is running upon leaving the page.

**Comment by frett** [comment]
ContentLoaders should be manage their own lifecycle and shut themselves done when the activity is finished and pause execution while the activity doesn't have focus.

**Comment by frett** [comment]
the data load callback may be triggered multiple times (based on how often fresh data is loaded).

**Comment by wrandall22** [comment]
The visual side effects of this have been fixed
